# Generated by Django 3.2.6 on 2021-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0005_alter_studentmarkdetails_stud_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='roll_number',
            field=models.IntegerField(unique=True),
        ),
    ]
