# Generated by Django 3.2.6 on 2021-08-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0006_alter_studentdetails_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
