# Generated by Django 3.2.6 on 2021-08-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0007_onlinepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
