# Generated by Django 3.2.6 on 2021-08-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0008_onlinepayment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
