# Generated by Django 3.2.6 on 2021-08-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0009_alter_onlinepayment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepayment',
            name='date',
        ),
    ]
