# Generated by Django 3.2.6 on 2021-08-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0012_auto_20210827_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
