# Generated by Django 3.2.6 on 2021-08-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0013_alter_onlinepayment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
