# Generated by Django 3.2.6 on 2021-08-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0014_onlinepayment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
