# Generated by Django 3.2.6 on 2021-08-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0015_amountbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountbalance',
            old_name='amount',
            new_name='bal_amount',
        ),
    ]
